name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-657a584f6459d400385f00f0-34fee2bbfc4952fa93c08cdc9a4d15ac48
      - name: Run API tests
        run: |
          postman collection run "7447686-8a60ae5b-4e00-44ab-8614-cfe2f12802f8"
